name: 'databricks_demo'
version: '1.0'
config-version: 2

profile: 'databricks_profile'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  databricks_demo:
    +catalog: workspace       
    bronze:
      +schema: bronze_schema  
      materialized: table
    silver:
      +schema: silver_schema 
      materialized: table
    gold:
      +schema: gold_schema   
      materialized: table

